### ISSUE TITLE
Item's inner bindings are not disposed when removed

### ISSUE THREAD

**Issue by AdamWillden** [brianmhunt/knockout-fast-foreach#15]
[Originally raised against knockout](https://github.com/knockout/knockout/issues/1701) but appears to be an issue with fast-foreach 

See console output of this fiddle (click remove):
http://jsfiddle.net/c3zqLmrb/
Vs console output of this fiddle (click remove):
http://jsfiddle.net/0or1xhme/

**Comment by brianmhunt** [comment]
Thanks Adam.

**Comment by brianmhunt** [comment]
Thanks for the great report @AdamWillden  - I think I know where this is occurring. Let me think about it and tinker for a bit.

**Comment by brianmhunt** [comment]
@AdamWillden What we want to be calling is [`ko.removeNode`](https://github.com/knockout/knockout/blob/624ddacd5a879ef5bf555d89e648f982a6bd6a4e/src/utils.domNodeDisposal.js#L82) or `ko.cleanNode` to remove or clean the node before removal.

Will update when the code when I get a chance, but please feel free to flip a PR along these lines.

Cheers
