### ISSUE TITLE
A more detail description about fast foreach binding?

### ISSUE THREAD

**Issue by cervengoc** [brianmhunt/knockout-fast-foreach#19]
Hello Biran, and first of all thank you for your efforts in this area. IMHO the foreach binding performance issues are one of the biggest downsides of knockoutjs currently, so I was really happy to see your project.

Could you put together a more detailed description on the GitHub homepage about your solution? I mean describe how it works, key differences with original foreach, notes about any limitations or "breaking change" what a developer should consider before simply switching to fastForeach. It would be really helpful, because now I can't make a decision wether I should try it or not.

**Comment by cervengoc** [comment]
Ok, I realized that it's not a huge amount of source code so I had a look and now have the idea. It means that there is nothing really urgent, for me at least :)

**Comment by brianmhunt** [comment]
Thanks @cervengoc – glad to see you've sorted your way through the code.

When I get a chance this plugin may be beefed up with docs and parity with the original binding provider.

Appreciate the interest, and I hope it's helpful. :)
