### ISSUE TITLE
Doesn't work data-bind="*: $data" on children

### ISSUE THREAD

**Issue by losogudok** [brianmhunt/knockout-fast-foreach#2]
When you have children with $data keyword fastForEach doesn't populate it with data.
Example:
http://jsfiddle.net/stgdmLf0/

**Comment by brianmhunt** [comment]
Thanks @losogudok – Figured it out -- issue at https://github.com/brianmhunt/knockout-fast-foreach/blob/master/index.js#L103

Cheers

**Comment by brianmhunt** [comment]
Also should be fixed. :smile: But appreciate a heads up with any issues. Cheers

**Comment by brianmhunt** [comment]
Incidentally, here's the result of the jsFiddle now:

```
slow: 275.460ms
fast: 2.155ms
```

**Comment by losogudok** [comment]
Thanks for fast reply! 
And about timing. You know it's not actually true because we are dealing with asynchronous events, but anyway fastForEach is faster than native. I'll do benchmarks later.

**Comment by brianmhunt** [comment]
Right you are on the async, I totally forgot to turn it off! Here's the jsFiddle with async turned off: http://jsfiddle.net/stgdmLf0/3/

Not much of an improvement:

```
slow: 232.668ms
fast: 201.330ms
```

Of course on the first run through they're doing the exact same thing – the advantage is with the adding and deletes.

It'd be really great to have some jsFiddles that demonstrate the difference. Just a couple thoughts:

For benchmarks, if you still want async (i.e. if you are checking differences [with reflows](http://wilsonpage.co.uk/preventing-layout-thrashing/)), you can add a callback to the frame animation e.g.

```
var frameAnimator = ko.bindingHandlers.fastForEach.FastForEach.animateFrame;
ko.bindingHandlers.fastForEach.FastForEach.animateFrame = function(frame) {
   frameAnimator()
   my_timing_function_ends() // <-- the frame has been updated now.
};
```

Cheers
