### ISSUE TITLE
Option for `animationFrame` vs `ko.tasks.schedule`

### ISSUE THREAD

**Issue by brianmhunt** [brianmhunt/knockout-fast-foreach#28]
Some may prefer to use `animationFrame` (better handling of bulk events); others `ko.tasks.schedule` (more immediate updates).

**Comment by brianmhunt** [comment]
This is already builtin, Brian.

``` javascript
ko.bindingHandlers.fastForeach.FastForEach.animateFrame = ko.tasks.schedule
```

**Comment by carlosagsmendes** [comment]
@brianmhunt can you further explain the difference? animationFrame is managed by the browser and my understanding is that it should be used to do UI updates. How does the ko.tasks.schedule work? Thanks in advance

**Comment by carlosagsmendes** [comment]
Sorry, I've just found this on [KO documentation](http://knockoutjs.com/documentation/microtasks.html).
