### ISSUE TITLE
Doesn't work with plain arrays.

### ISSUE THREAD

**Issue by losogudok** [brianmhunt/knockout-fast-foreach#3]
If data for fastForEach is normal array, script will raise an error.
The problem is in line 51.

``` javascript
  ko.utils.arrayForEach(this.data(), function (item) {
    self.changeQueue.push({
      index: primeIdx++,
      status: "added",
      value: item
    });
  })
```

**Comment by brianmhunt** [comment]
Thanks @losogudok - I'll get to this one ASAP, but feel free to send a PR, too.

Cheers

**Comment by brianmhunt** [comment]
Should be fixed - let me know if you have any issues. Cheers.

**Comment by losogudok** [comment]
Thanks! I'd like to contribute but first I need to understand how Ko works inside.

**Comment by brianmhunt** [comment]
Thanks @losogudok – KO is a pretty hefty project, but I'm always eager to help if you have any questions.

Some benchmarks on jsFiddle would also be very good at illustrating the point of this plugin.

Cheers!
