### ISSUE TITLE
Does not work on virtual elements

### ISSUE THREAD

**Issue by AdamWillden** [brianmhunt/knockout-fast-foreach#4]
Not sure if there's a particular reason but this doesn't work on virtual elements.

```
The binding 'fastForEach' cannot be used with virtual elements;
View: shell;
ModuleId: shell
```

**Comment by brianmhunt** [comment]
Thanks for the report, Adam. I just thought of that this morning.

There are two reasons, one substantive. The first is that  we need  to set `ko.virtualElements.allowedBindings.fastForEach = true;` (just to tell KO that we have built this binding with virtual elements in mind.

The second is to build the binding with virtual elements in mind. :) As far as I can see so far, it's just a matter of changing the [`spec.element.cloneNode`](https://github.com/brianmhunt/knockout-fast-foreach/blob/master/index.js#L19) to the rough [equivalent for virtual elements](https://github.com/knockout/knockout/blob/master/src/virtualElements.js#L27).

**Comment by AdamWillden** [comment]
Yeah I had just tried adding the allowedBindings to see if that's all that was missing. Unfortunately not so lucky!

**Comment by brianmhunt** [comment]
Shouldn't be too hard to fix; on it now. :)

**Comment by brianmhunt** [comment]
Should be fixed; let me know if you have any issues, Adam. Cheers

**Comment by AdamWillden** [comment]
0.2 looks good in terms of this issue. Thanks.

I think I'm facing other issues now will post new issues soon once I determine whats happening.

**Comment by AdamWillden** [comment]
Should I assume the aim is to swap any foreach bindings for fastForEach without issues?

**Comment by brianmhunt** [comment]
@AdamWillden - Many thanks, much appreciated. Yes exactly re. swapping for `foreach`, subject to #1 (i.e. `$index` not _yet_ working, and needing a bit of thought).
