### ISSUE TITLE
Cannot update individual array items

### ISSUE THREAD

**Issue by Hainesy** [brianmhunt/knockout-fast-foreach#40]
Previously, using the standard foreach binding, I was updating individual records in an observable array by using the following code:

```
var index = myObservableArray.indexOf(updatedItem);
if (index >= 0) {
    myObservableArray.splice(index, 1);
    myObservableArray.splice(index, 0, updatedItem);
}
```

However, switching to fastForEach and it doesn't update the UI. So I have attempted to notify the UI that the entire array has changed and even that doesn't seem to work:

```
var rawData = myObservableArray();
myObservableArray(rawData);
```

Even this doesn't work:

```
var rawData = myObservableArray();
myObservableArray([]);
myObservableArray(rawData);
```

The only thing that works is the below, but it causes an undesirable flash in the UI:

```
var rawData = myObservableArray();
myObservableArray([]);
setTimeout(function() {
    myObservableArray(rawData);
}), 1;
```

Any ideas on how to reflect changes to individual items of an observableArray in the UI?

**Comment by cervengoc** [comment]
Could you please clarify what kind of "update" do you mean?

In general, each individual item has its own nodes with its bindings, which is encapsulated within a new childcontext. Those bindings should reflect changes made within the item. I mean there should not be need to remove and reinsert the item.

Anyway, I think the UI is not updating due to the move detection which was implemented in the last release. FastForEach detects that you reinserted the same item, so it reuses the same nodes. Same goes for reinserting the entire array.

**Comment by Hainesy** [comment]
The items in the observable array are not observables but native JavaScript objects. I have changed one of the items in the underlying array and am trying to rebind the entire array but no matter what I do I can't get it to update in the UI. What mechanism is it using to detect that the item is "the same"?

**Comment by cervengoc** [comment]
I suggest using one of these techniques.
- Use observable properties.
- Wrap each item in an observable and use a with binding around them. Then
  if you set it to null and then reassign it, the UI should react. Later I
  can create a fiddle if you need to demonstrate this.

**Comment by brianmhunt** [comment]
Would knockout-es5 help here?

**Comment by Hainesy** [comment]
Both those options will require quite a lot of changes - is there another
option that I can hack in quickly for now?

**Comment by Hainesy** [comment]
@brianmhunt I'm not sure how?

**Comment by cervengoc** [comment]
You can override the `shouldDelayDeletion` function, which is behind the scenes in item move detection.

```
FastForEach.prototype.shouldDelayDeletion = function (data) {
  return false;
};
```

@brianmhunt I'm still thinking about wether it's reasonable to allow turn on or off the move detection. In my opinion this case is quite special use-case, generally in a good Knockout model design the move detection mustn't be a problem. What do you think?

**Comment by cervengoc** [comment]
Sorry, the correct way to override that function is this.

```
ko.bindingHandlers.fastForEach.FastForEach.prototype.shouldDelayDeletion = function (data) {
  return false;
};
```

Put this code before any bindings get applied.

**Comment by brianmhunt** [comment]
Definitely agree re. move detection.

**Comment by cervengoc** [comment]
@Hainesy did you manage to solve this? If yes, can this be closed?

**Comment by Hainesy** [comment]
In the end I resolve my issue a different way by cloning and re-inserting the objects I wanted to change. Not very elegant, but I'd prefer not to override library methods as it makes it harder to up date. Personally I feel this is a bug or oversight in the library, but the performance benefits outweigh the inconvenience of having to account for this in my code.
