### ISSUE TITLE
Using fastForEach makes ko.applyBindings asynchronous

### ISSUE THREAD

**Issue by cervengoc** [brianmhunt/knockout-fast-foreach#41]
I currently struggled a bit with this. I'm trying to do something like this.

```
var $node = $("<div data-bind='fastForEach: items'/>");
ko.applyBindings({ items: [1, 2, 3, 4] }, $node.get(0));
var height = $node.height(); // <-- here it reports 0 because nodes are not rendered yet
```

Maybe this is acceptable, but quite tricky to work around in some situations, and I don't like the fact that the DOM is not ready right after `applyBindings`, and I think most developers might get confused if they meet such scenario. As far as I know, this kind of synchronous behavior is present using every other binding, but correct me if I'm wrong.

Maybe it would be good idea to process the initial rendering synchronously. The main point of being asynchronous is to be able to optimize array **changes**, so it should fit into the design I think.

What do you think @brianmhunt about this?

PS: It would also eliminate the frustrating stuttering effect in the browser when applying bindings with a more complex model.

**Comment by brianmhunt** [comment]
Hey @cervengoc – I thought about this quite a bit.

I think the most future-proof option will be to have `applyBindings` return a promise, which I'm working on for [knockout/tko](knockout/tko).  So the solution would be simple and canonical ES6:

``` javascript
var $node = $("<div data-bind='fastForEach: items'/>");
ko.applyBindings({ items: [1, 2, 3, 4] }, $node.get(0))
   .then(function () {
      var height = $node.height();
   })
```

The stuttering is a different, but also important, problem.  I think the fix will be on a per-binding basis, or perhaps with "helper" bindings that pre-allocate space for async bindings.  Not sure yet -- need to see some examples, but I'm with you in thinking it's a problem.

What do you think?

**Comment by cervengoc** [comment]
Yeah I was also thinking about returning a promise, not bad at all, but perhaps it's not worth the architectural changes needed (I guess it's big work to implement some kind of notification per binding).

I personally think that it would be more convenient and simpler to stay with the synchronous behavior of `applyBindings`.

As far as stuttering goes, it can also be handled a covering backdrop and a loading panel for example. That's what I do currently.

**Comment by cervengoc** [comment]
So what about changing the current version (which targets 3.4) so that it would handle initial rendering synchronously? It doesn't seem to be a huge code change. Actually I've tested it already. 

I think it would be more straightforward for this time and this version, and we can still accommodate to future changes without too much work.

**Comment by brianmhunt** [comment]
I'm ok with that :)
