### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'

### ISSUE THREAD

**Issue by AdamWillden** [brianmhunt/knockout-fast-foreach#5]
Using 0.2.

I have a page by option which if I lower (pag by 15 to page by 5 - removing last 10 items from the currrent collection) I get an exception `Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`.

This line returns undefined trying to access index [134] of 134 items: 
https://github.com/brianmhunt/knockout-fast-foreach/blob/master/dist/knockout-fast-foreach.js#L145 

If I need to supply more details let me know.

**Comment by brianmhunt** [comment]
Thanks Adam. This would seem to be an off-by-one error. Any chance you could post a jsFiddle or jsBin that illustrates? (Here's a [sample jsfiddle](http://jsfiddle.net/stgdmLf0/) from #2 that could be a good base.) I can't glean exactly where the problem stems from just from the description.

Cheers

**Comment by AdamWillden** [comment]
http://jsfiddle.net/zfqj5rb7/ :-)

**Comment by brianmhunt** [comment]
This looks fixed too - same as #5.

Thanks so much @AdamWillden – definitely would not have progressed as far on this plugin today without all your feedback. Very sincerely appreciated.

:beers:
